home/urls.py
from django.contrib import admin
from django.urls import path,include
# import features
from features.views import search,getTrains,schedule,getTinfo,addR,addST,addRT,addT,cva,cn,cancel,book,book1,pnr
from .views import home
app_name='home'
urlpatterns = [
    path('user',home,name="home" ),
    
    path('search/', search, name='search'),
    path('search/trains', getTrains, name='get-trains'),
    path('schedule/', schedule, name='schedule'),
    path('schedule/trains', getTinfo, name='get-trains'),
    path('addR/', addR, name="addR"),
    path('addST/', addST, name='add-station'),
    path('addT/', addT, name='add-train'),
    path('addRT/',addRT),
    path('search/search/trains/cva/', cva,name='cva'),
    path('search/book1/', book1,name='book1'),
    path('search/book1/book/', book,name='book'),
    path('cancel/',cancel,name='cancel'),
    path('cancel/cancel/cn/',cn,name='cancl'),
    path('pnr/',pnr,name="pnr"),
    ]

railway/urls.py
from django.contrib import admin
from django.urls import path,include
from features import views
from home import views
app_name='basic'
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.log,name='log'),
    # path('register/',views.Reg,name="reg"),
    # path('logout/',views.logout,name="logout"),
    path('home/',include('home.urls',namespace="home"),name="home"),
    path('',include('authentication.urls')),

]

templates/_partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>


        {% block title %}

        
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">


    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">

    <style>
        body{
            background-image:url('{% static "images/hompage.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;


        }
        .sty
        {
            font-family: 'Dancing Script', cursive;
            color:white;
        }
        .hd
        {
            margin-left:400px;

            }
         .tform{
            background-color:rgba(0,0,0,0.3);
            }
            .fpnr
            {
                width:20%;
                margin-left:500px;
                margin-top:150px;
                padding:15px;
                background-color:rgba(0,0,0,0.3);
                }

        .tick{
            width:20%;
            height:150px;
           background-image:url('{% static "images/ticket6"%}');
            background-size:100% 100%;
            background-repeat:no-repeat;
            }

            body{
            background-image:url('{% static "images/hompage.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;
        }
        .sty
        {
            font-family: 'Dancing Script', cursive;
            color:white;
        }
        .row1{




            background-color:rgba(0,0,0,0.6);


        }

            
            
    </style>

</head>
<body>

<div>
{% include "_partials/header.html" %}


<div class="ui container">
    {% block content%}


    {% endblock content%}

    {% block body %}


    {% endblock %}



</div>

   
</div>


    
</body>
</html>

templates/_partials/header.html
{%load static %}

<div class="ui menu">
  <div class="ui container">
    <a href={% url 'login' %} class="header item">
      <img class="logo" class="logo" src= {% static 'img/Logo.png' %} />
    </a>


    <div class="right item">
      {% if request.user.is_authenticated %}
      <a href={% url 'home:book1' %} class="ui primary button">Book Train</a>
      <div class="ui simple dropdown item">
         {{request.user.username}} <i class="dropdown icon"></i>
        <div class="menu">
        <form class="ui large form" method="post" action={% url 'logout_user' %}>

          {% csrf_token %}
         <input class="ui button"
              type="submit"
              value="Sign out"
            />
          </form>
        </div>
      </div>

      {% else %}
      <div class="ui item">
      <a href={% url 'login' %} class="ui primary button">Login</a>
      </div>
      
      <div class="ui item">
      <a href={% url 'register' %} class="ui primary button">Register</a>
      </div>

      {% endif %}
    </div>
  </div>
</div>

templates/_partials/messages.html
{% if messages %}


{% for message in messages %}


<div class="ui {{message.tags}} message">

    {{message}}


</div>



{% endfor %}




{% endif %}